/* Wolof (wo) — partial interface translation keyed on the French string; anything missing falls back to French.
   Standard CLAD orthography. To be reviewed by a native speaker before any real use. */
const WO={
 /* navigation & sections */
 'Tableau de bord':'Tablo bi','Licences':'Lisãs yi','Licenciés':'Ñi am lisãs','Renouvellements':'Yeesal yi','Compétitions':'Joŋante yi','Bilans':'Njureef yu gën','Clubs':'Kulëb yi','Administration':'Caytu gi','Feuille de route':'Yoonu liggéey bi','Retours':'Xalaat yi','Ma carte':'Sama kàrt','Vérification':'Saytu',
 'Demandes de licence':'Laaju lisãs yi','Expirations & relances':'Lisãs yu jeex ak fàttali','Statistiques':'Lim yi','Utilisateurs & rôles':'Jëfandikukat yi ak seeni wàll','Permissions':'Sañ-sañ yi','Paramètres':'Tànneef yi','Journal d’activité':'Téereb jëf yi','Retours sur le prototype':'Xalaat ci prototip bi',
 'Ma carte d’identité sportive':'Sama kàrtu tàggat-yaram','Accueil':'Xët wu njëkk','Retour':'Dellu','Calendrier':'Arminaat','Résultats':'Njureef yi','Vérifier une licence':'Saytu ab lisãs','Date de démo':'Bésu demo bi',
 'Au quotidien':'Bés bu nekk','Suivi':'Topp','Prototype':'Prototip','Changer de profil':'Soppi profil','Fermer':'Tëj','Réinitialiser la démo':'Tàmbaliwaat demo bi',
 'Voir en tant que':'Gise ni','Admin':'Admin','Ligue':'Lig','Club':'Kulëb','Officiel':'Àttekat','Athlète':'Tàggatkatu-yaram',
 /* login */
 'Une licence, une carrière, un seul registre.':'Benn lisãs, benn yoonu tàggat-yaram, benn téere kese.','Choisissez un profil':'Tànnal ab profil','Prototype · données fictives':'Prototip · ay lim yu dul dëgg','clubs affiliés':'kulëb yu bokk','licenciés':'ñu am lisãs','régions':'diiwaan','performances':'njureef',
 /* roles */
 'Super admin fédération':'Njiitu caytu federaasioŋ bi','Agent licences':'Liggéeykatu lisãs yi','Ligue régionale':'Ligu diiwaan','Responsable de club':'Njiitu kulëb','Officiel / juge':'Àttekat','Athlète licencié':'Tàggatkatu-yaram bu am lisãs',
 /* dashboard */
 'Bonjour':'Jàmm nga am','saison':'sezoŋ','Demander une licence':'Laaj ab lisãs','Créer un événement':'Sos ab joŋante','Commencer':'Tàmbali','Créer':'Sos','Ouvrir':'Ubbi','Voir':'Xool',
 'Licenciés en règle':'Ñi seen lisãs baax','Demandes à instruire':'Laaj yi ñu war a saytu','Licences à renouveler':'Lisãs yi ñu war a yeesal','Compléments à fournir':'Kayit yi des','au registre':'ci téere bi','sur':'ci','jours':'fan','expirent dans':'dinañu jeex ci',
 'Résultats du week-end':'Njureefi njeexitalu ayu-bés bi','Tous les résultats':'Njureef yépp','Top 5 des performances de l’année':'5 njureef yi gën ci at mi','3 prochains événements':'3 joŋante yi di ñëw','Campagne':'Kàmpaañ','Relancer les licenciés':'Fàttali ñi am lisãs','À instruire':'Li ñu war a saytu','Demandes du club':'Laaji kulëb bi','Tout voir':'Xool lépp','Rien à traiter':'Amul dara lu ñu war a def',
 'Licenciés par région':'Ñi am lisãs ci diiwaan bu nekk','Pyramide des catégories':'Xeeti at yi','Femmes':'Jigéen','Hommes':'Góor','Femmes / hommes par catégorie':'Jigéen / góor ci xeet bu nekk',
 /* statuses */
 'Brouillon':'Mbind mu jeexul','Soumise':'Yónnee nañu ko','En instruction':'Ñu ngi koy saytu','Complément demandé':'Laaj nañu yeneen kayit','Validée':'Nangu nañu ko','Refusée':'Bañ nañu ko','Active':'Mu ngi dox','Expire bientôt':'Dina jeex léegi','Expirée':'Jeex na','Suspendue':'Taxawal nañu ko',
 'Engagements ouverts':'Bindu ubbi na','Engagements clos':'Bindu tëj na','Résultats publiés':'Njureef yi génn nañu','Inscrite au calendrier':'Bind nañu ko ci arminaat bi','En attente de validation':'Mu ngi xaar ñu nangu ko','Résultats en saisie':'Ñu ngi bind njureef yi',
 /* common actions & labels */
 'Nouvelle demande de licence':'Laaju lisãs bu bees','Nouvelle demande':'Laaj bu bees','Enregistrer':'Denc','Annuler':'Bàyyi','Continuer':'Wéy','Précédent':'Dellu ginnaaw','Envoyer':'Yónnee','Modifier':'Soppi','Imprimer':'Móol','Renouveler':'Yeesal','Suspendre':'Taxawal','Réactiver':'Doxalaat','Copier':'Sotti','Exporter CSV':'Génne CSV','Rechercher':'Seet','Tout':'Lépp','Toutes':'Yépp',
 'Identité':'Kan la','Coordonnées':'Fu ñu koy gise','Pratique':'Tàggat-yaram','Pièces':'Kayit yi','Récapitulatif':'Tënk','Paiement':'Peyoor','Moyen de paiement':'Anamu fey','À régler':'Li ñu war a fey','Payer':'Fey','Paiement reçu':'Jot nañu peyoor bi','Paiement confirmé':'Peyoor bi wóor na','Nom':'Sant','Prénom':'Tur','Prénom(s)':'Tur','Sexe':'Góor walla jigéen','Féminin':'Jigéen','Masculin':'Góor','Date de naissance':'Bés bi mu juddoo','Jour':'Bés','Mois':'Weer','Année':'At','Lieu de naissance':'Fa mu juddoo','Nationalité':'Réew','Téléphone':'Telefon','Adresse':'Dëkkuwaay','Région':'Diiwaan','Ville':'Dëkk','Épreuves':'Xeeti joŋante','Épreuve':'Xeetu joŋante','Catégorie':'Xeetu at','Statut':'Tolluwaay','Performance':'Njureef','Vent':'Ngelaw','Place':'Raŋ','Lieu':'Béréb','Date':'Bés','Points':'Poñ','Niveau':'Tolluwaay',
 'Pièces justificatives':'Kayit yi ñu laaj','Décision':'Dogal','Valider et attribuer le numéro':'Nangu te jox ko limu lisãs','Demander un complément':'Laaj yeneen kayit','Refuser la demande':'Bañ laaj bi','Règlement':'Peyoor','Historique':'Li xewoon','Identité & coordonnées':'Kan la ak fu ñu koy gise',
 'Carte & profil':'Kàrt ak profil','Bilan':'Tënku sezoŋ bi','Documents':'Kayit yi','Records personnels':'Njureef yi mu gën a def','Profil':'Profil','Cliquez sur la carte pour la retourner':'Bësal ci kàrt bi ngir wëlbati ko','Licence valide':'Lisãs bi baax na','Licence expirée':'Lisãs bi jeex na','Licence suspendue':'Lisãs bi taxawal nañu ko','Licence inconnue':'Lisãs bii xamuñu ko','Vérifier':'Saytu',
 'Calendrier des compétitions':'Arminaatu joŋante yi','En ce moment & à venir':'Léegi ak li di ñëw','Mes événements':'Sama joŋante yi','Vue mensuelle':'Weer wi','Fiche d’identité':'Kayitu xamle','Programme':'Porogaraam','Engagements':'Ñi bindu','Listes de départ':'Limu ñiy tàmbali','Banque d’images':'Dencukaayu nataal','Fiche':'Kayit','Libellé':'Tur wi','État':'Tolluwaay',
 'Recherche par épreuve':'Seet ci xeetu joŋante','Classement des clubs':'Raŋu kulëb yi','Records & homologations':'Rekoor yi','Records du Sénégal':'Rekoori Senegaal','Clubs affiliés':'Kulëb yi bokk','Registre des licenciés':'Téereb ñi am lisãs','Aller plus loin que les leaders':'Gën a sori ñi jiitu','Dans le prototype':'Ci prototip bi','Proposé':'Li ñu digle','Donner un avis':'Joxe sa xalaat'};
