/* ============ statistics — everything is computed from the scoped register, never hard-coded ============ */
function pageStats(params){const ppl=myPeople(),ids=new Set(ppl.map(p=>p.id)),clubs=myClubs(),all=ME.scope.kind==='all';
 const cur=ppl.filter(p=>p.licences.some(l=>l.season===DB.season.current));const pct=(a,b)=>b?Math.round(a/b*100):0;
 const women=cur.filter(p=>p.sex==='F').length,youth=cur.filter(p=>['U12','U14','U16','U18','U20'].includes(catOf(p.dob))).length;
 const prev=ppl.filter(p=>p.licences.some(l=>l.season==='2024-2025')),kept=prev.filter(p=>p.licences.some(l=>l.season===DB.season.current)).length;
 const firstTimers=cur.filter(p=>p.licences.length===1||p.since>=2025).length;
 /* licences per season */
 const seasons=[];for(let y=2019;y<=2025;y++)seasons.push(`${y}-${y+1}`);
 const perSeason=seasons.map(s=>{const n=ppl.filter(p=>p.licences.some(l=>l.season===s)).length;return {x:s.slice(2,5)+s.slice(7),y:n,tip:`${s} : ${n.toLocaleString('fr-FR')} ${tr('licences','licences')}`}});
 /* age pyramid */
 const pyr=CATS.map(c=>{const x=cur.filter(p=>catOf(p.dob)===c.code);return {l:`${c.code} · ${catLabel(c.code)}`,v:[x.filter(p=>p.sex==='F').length,x.filter(p=>p.sex==='M').length]}});
 const types=Object.keys(LIC_TYPES).map(k=>({l:licType(k).split(' (')[0],v:[cur.filter(p=>p.type===k).length],href:'licensees?type='+k})).sort((a,b)=>b.v[0]-a.v[0]);
 /* sport */
 const res=DB.results.filter(r=>ids.has(r.a)&&r.st==='OK'&&COMP(r.compId)?.status==='published');
 const byGroup=Object.keys(GROUPS).map(g=>{const x=res.filter(r=>EV(r.code).group===g);return {l:tr(...GROUPS[g]),v:[x.filter(r=>r.sex==='F').length,x.filter(r=>r.sex==='M').length]}}).sort((a,b)=>(b.v[0]+b.v[1])-(a.v[0]+a.v[1]));
 const best={};res.forEach(r=>{if(!legal(r))return;const v=points(r.code,r.sex,r.perf);if(!(best[r.a]>=v))best[r.a]=v});
 const LV=['IA','N1','N2','N3','IR','R1','R2','D'],byLevel=LV.map(l=>{const n=Object.values(best).filter(v=>levelOf(v)===l).length;return {l,v:n,tip:`${tr('Niveau','Level')} ${l} : ${n} ${tr('athlètes','athletes')}`,hl:l==='IA'||l==='N1'}});
 const months=['2025-12','2026-01','2026-02','2026-03','2026-04','2026-05','2026-06','2026-07','2026-08','2026-09'].map(m=>{const n=res.filter(r=>r.date.startsWith(m)).length;return {l:D.mon3(m+'-01'),v:n,tip:`${D.month(m+'-01')} : ${n} ${tr('performances','marks')}`}});
 const competing=new Set(res.map(r=>r.a)).size,compLic=cur.filter(p=>['competition','jeunes'].includes(p.type)).length;
 /* applications */
 const apps=myApps(),decided=apps.filter(a=>a.decidedAt&&a.submittedAt),delay=decided.length?(decided.reduce((s,a)=>s+D.diff(a.decidedAt.slice(0,10),a.submittedAt.slice(0,10)),0)/decided.length):0;
 const pay={};apps.filter(a=>a.paid?.method).forEach(a=>{pay[a.paid.method]=(pay[a.paid.method]||0)+1});const payRows=Object.entries(pay).sort((a,b)=>b[1]-a[1]).map(([l,n])=>({l,v:[n]}));
 const rej={};apps.forEach(a=>Object.entries(a.docs||{}).forEach(([k,d])=>{if(['rejected','missing'].includes(d.status)&&a.status!=='draft')rej[k]=(rej[k]||0)+1}));
 /* regions / clubs table */
 const rows=(all?REGIONS.map(r=>({key:r.code,name:r.name,href:'licensees?region='+r.code,ppl:cur.filter(p=>p.region===r.code),clubs:clubs.filter(c=>c.region===r.code).length})):clubs.map(c=>({key:c.id,name:c.name,href:'clubs/'+c.id,ppl:cur.filter(p=>p.clubId===c.id),clubs:1}))).map(r=>{const pid=new Set(r.ppl.map(p=>p.id)),rr=res.filter(x=>pid.has(x.a));return {...r,n:r.ppl.length,w:pct(r.ppl.filter(p=>p.sex==='F').length,r.ppl.length),y:pct(r.ppl.filter(p=>['U12','U14','U16','U18','U20'].includes(catOf(p.dob))).length,r.ppl.length),ren:pct(r.ppl.filter(renewed).length,r.ppl.length),marks:rr.length,top:Math.max(0,...rr.filter(legal).map(x=>points(x.code,x.sex,x.perf)))}}).filter(r=>r.n).sort((a,b)=>b.n-a.n);
 const maxN=Math.max(1,...rows.map(r=>r.n));
 const exp=()=>csv([[all?'region':'club','clubs','licencies','pct_femmes','pct_jeunes','pct_renouveles','performances','meilleur_indice']].concat(rows.map(r=>[r.name,r.clubs,r.n,r.w,r.y,r.ren,r.marks,r.top])));window.__statsCsv=exp;
 return `<div class="head"><div><h1>${tr('Statistiques','Statistics')}</h1><div class="sub">${esc(scopeLabel(ME))} · ${tr('saison','season')} ${DB.season.current} · ${tr('calculées en direct sur le registre, les demandes et les résultats publiés','computed live from the register, applications and published results')}</div></div><div class="actions"><button class="btn" onclick="exportBox('${tr('Statistiques par territoire (CSV)','Statistics by territory (CSV)')}',window.__statsCsv())">${ic('download')} ${tr('Exporter CSV','Export CSV')}</button></div></div>
 <div class="grid g4 stagger" style="margin-bottom:16px">${kpi(tr('Licenciés','Licensees')+' '+DB.season.current,cur.length,`${clubs.length} clubs · ${(cur.length/Math.max(1,clubs.length)).toFixed(1)} ${tr('par club','per club')}`,'users')}${kpi(tr('Part des femmes','Share of women'),pct(women,cur.length)+' %',`${women.toLocaleString('fr-FR')} ${tr('licenciées','women')}`,'venus','warn')}${kpi(tr('Moins de 20 ans','Under 20'),pct(youth,cur.length)+' %',`${youth.toLocaleString('fr-FR')} ${tr('jeunes (U12 à U20)','young athletes (U12–U20)')}`,'sprout','info')}${kpi(tr('Fidélisation','Retention'),pct(kept,prev.length)+' %',`${tr('des licenciés 2024-25 ont repris en','of 2024-25 licensees came back in')} 2025-26`,'repeat')}</div>
 <div class="grid g-23" style="margin-bottom:16px"><div class="panel"><div class="hd"><h2>${tr('Licences par saison','Licences per season')}</h2><span class="muted sm">${firstTimers.toLocaleString('fr-FR')} ${tr('premières licences cette saison','first-time licences this season')}</span></div><div class="bd">${lineChart(perSeason,{fmt:v=>Math.round(v).toLocaleString('fr-FR'),label:'licences per season'})}</div></div>
 <div class="panel"><div class="hd"><h2>${tr('Types de licence','Licence types')}</h2></div><div class="bd">${hbars(types)}</div></div></div>
 <div class="grid g2" style="margin-bottom:16px"><div class="panel"><div class="hd"><h2>${tr('Pyramide des âges','Age pyramid')}</h2></div><div class="bd">${hbars(pyr,{colors:['var(--c2)','var(--c1)'],legend:[tr('Femmes','Women'),tr('Hommes','Men')]})}</div></div>
 <div class="panel"><div class="hd"><h2>${tr('Performances par famille d’épreuves','Marks by event group')}</h2><span class="muted sm">${res.length.toLocaleString('fr-FR')} ${tr('performances publiées','published marks')}</span></div><div class="bd">${hbars(byGroup,{colors:['var(--c2)','var(--c1)'],legend:[tr('Femmes','Women'),tr('Hommes','Men')]})}</div></div></div>
 <div class="grid g2" style="margin-bottom:16px"><div class="panel"><div class="hd"><h2>${tr('Densité par niveau','Depth by level')}</h2><span class="muted sm">${tr('meilleur indice de chaque athlète','each athlete’s best index')}</span></div><div class="bd">${colChart(byLevel,{label:'levels'})}<p class="sm muted" style="margin-top:8px">${competing.toLocaleString('fr-FR')} ${tr('athlètes ont concouru, soit','athletes competed, i.e.')} <b style="color:var(--ink)">${pct(competing,compLic)} %</b> ${tr('des licences compétition et jeunes.','of competition and youth licences.')}</p></div></div>
 <div class="panel"><div class="hd"><h2>${tr('Activité compétitive par mois','Competition activity per month')}</h2></div><div class="bd">${colChart(months,{label:'marks per month'})}</div></div></div>
 <div class="grid g3" style="margin-bottom:16px"><div class="panel"><div class="hd"><h2>${tr('Instruction des demandes','Application processing')}</h2></div><div class="bd"><dl class="dl">${[[tr('Délai moyen de décision','Average time to decision'),delay.toFixed(1)+' '+tr('jours','days')],[tr('Taux de validation','Approval rate'),pct(apps.filter(a=>a.status==='approved').length,decided.length)+' %'],[tr('Demandes de la campagne','Campaign applications'),apps.filter(a=>a.status!=='draft').length],[tr('Avec complément demandé','With documents requested'),apps.filter(a=>a.history.some(h=>h.action==='info_requested')).length]].map(([k,v])=>`<div><dt>${k}</dt><dd style="font-size:18px">${v}</dd></div>`).join('')}</dl></div></div>
 <div class="panel"><div class="hd"><h2>${tr('Moyens de paiement','Payment methods')}</h2></div><div class="bd">${payRows.length?hbars(payRows):`<span class="muted sm">—</span>`}<p class="xs muted" style="margin-top:8px">${tr('Le mobile money domine : argument pour l’intégrer au parcours.','Mobile money dominates: a case for building it into the flow.')}</p></div></div>
 <div class="panel"><div class="hd"><h2>${tr('Pièces qui bloquent le plus','Documents that block most')}</h2></div><div class="bd">${Object.keys(rej).length?hbars(Object.entries(rej).sort((a,b)=>b[1]-a[1]).map(([k,n])=>({l:{medical:tr('Certificat médical','Medical certificate'),parental:tr('Autorisation parentale','Parental consent'),transfer:tr('Lettre de sortie','Release letter'),photo:'Photo',idcard:tr('Pièce d’identité','ID document'),form:tr('Fiche signée','Signed form'),payment:tr('Justificatif de paiement','Proof of payment'),diploma:tr('Diplôme','Certificate')}[k],v:[n]})),{colors:['var(--c2)']}):`<span class="muted sm">${tr('Aucune pièce refusée ou manquante.','No rejected or missing document.')}</span>`}</div></div></div>
 <div class="flat"><div class="mchip dark">${all?tr('Par ligue régionale','By regional league'):tr('Par club','By club')}</div><div class="tblw"><table><thead><tr><th>${all?tr('Ligue','League'):'Club'}</th>${all?'<th class="num">Clubs</th>':''}<th>${tr('Licenciés','Licensees')}</th><th class="num">% ${tr('femmes','women')}</th><th class="num hide-m">% U20-</th><th class="num hide-m">% ${tr('renouvelés','renewed')}</th><th class="num hide-m">${tr('Performances','Marks')}</th><th class="num hide-m">${tr('Meilleur indice','Best index')}</th></tr></thead><tbody>${rows.slice(0,all?14:20).map(r=>`<tr class="link" data-go="${r.href}"><td><b>${esc(r.name)}</b></td>${all?`<td class="num">${r.clubs}</td>`:''}<td><span class="row" style="flex-wrap:nowrap;gap:10px"><span class="hbar" style="grid-template-columns:minmax(60px,160px);padding:0"><span class="trk" style="background:none;width:${Math.max(3,r.n/maxN*100)}%"><i style="flex:1;background:var(--c1)"></i></span></span><b class="tnum">${r.n.toLocaleString('fr-FR')}</b></span></td><td class="num">${r.w} %</td><td class="num hide-m">${r.y} %</td><td class="num hide-m">${r.ren} %</td><td class="num hide-m">${r.marks.toLocaleString('fr-FR')}</td><td class="num hide-m">${r.top||'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
