export type Ep = { t: string; s: string; tech: string[]; wr: [string, string, string, string][]; sen: [string, string, string, string][] };
export const EP: Ep[] = [
  { t: "Sprint", s: "100 m · 200 m · 400 m", tech: ["Couloirs de 1,22 m, starting-blocks obligatoires jusqu'au 400 m.", "Vent mesuré sur 100 et 200 m : au-delà de +2,0 m/s, la performance n'est pas homologable.", "Temps de réaction inférieur à 0,100 s = faux départ."], wr: [["H", "100 m — Usain Bolt", "Berlin 2009", "9″58"], ["F", "100 m — Florence Griffith-Joyner", "Indianapolis 1988", "10″49"], ["H", "400 m — Wayde van Niekerk", "Rio 2016", "43″03"], ["F", "400 m — Marita Koch", "Canberra 1985", "47″60"]], sen: [["F", "400 m — Amy Mbacké Thiam", "Edmonton 2001", "49″86"], ["H", "400 m — Ibou Faye", "Zurich 1995", "44″94"]] },
  { t: "Haies", s: "100 m H · 110 m H · 400 m H", tech: ["110 m haies : 10 obstacles de 1,067 m, espacés de 9,14 m.", "100 m haies femmes : 10 obstacles de 0,838 m, espacés de 8,50 m.", "400 m haies : 10 obstacles, 35 m d'intervalle, hauteur 0,914 m (H) et 0,762 m (F)."], wr: [["H", "110 m H — Aries Merritt", "Bruxelles 2012", "12″80"], ["F", "100 m H — Tobi Amusan", "Eugene 2022", "12″12"], ["H", "400 m H — Karsten Warholm", "Tokyo 2021", "45″94"], ["F", "400 m H — Sydney McLaughlin-Levrone", "Eugene 2024", "50″37"]], sen: [["H", "400 m H — Amadou Dia Ba", "Séoul 1988", "47″23"], ["H", "110 m H — Louis François Mendy", "Kinshasa 2023", "13″33"]] },
  { t: "Demi-fond", s: "800 m · 1 500 m", tech: ["800 m : départ en couloirs, rabattement autorisé après 100 m.", "1 500 m : départ groupé sur ligne courbe, 3 tours ¾.", "Aucune limite de vent : les performances sont homologables par tout temps."], wr: [["H", "800 m — David Rudisha", "Londres 2012", "1'40″91"], ["F", "800 m — Jarmila Kratochvílová", "Munich 1983", "1'53″28"], ["H", "1 500 m — Hicham El Guerrouj", "Rome 1998", "3'26″00"], ["F", "1 500 m — Faith Kipyegon", "Paris 2024", "3'49″04"]], sen: [["H", "800 m — Babacar Niang", "Nice 1985", "1'44″06"], ["F", "1 500 m", "à renseigner", "—"]] },
  { t: "Fond", s: "5 000 m · 10 000 m", tech: ["5 000 m : 12 tours et demi. 10 000 m : 25 tours.", "Ravitaillement en eau autorisé sur 10 000 m au-delà de certaines conditions de chaleur.", "Départ groupé, classement au photo-finish."], wr: [["H", "5 000 m — Joshua Cheptegei", "Monaco 2020", "12'35″36"], ["F", "5 000 m — Gudaf Tsegay", "Eugene 2023", "14'00″21"], ["H", "10 000 m — Joshua Cheptegei", "Valence 2020", "26'11″00"], ["F", "10 000 m — Letesenbet Gidey", "Hengelo 2021", "28'54″14"]], sen: [["H", "5 000 m", "à renseigner", "—"], ["F", "10 000 m", "à renseigner", "—"]] },
  { t: "Marche athlétique", s: "10 km · 20 km", tech: ["Contact permanent avec le sol à l'œil nu : jamais de phase de suspension visible.", "Jambe avant tendue du contact au passage à la verticale.", "Trois cartons rouges de juges différents : pénalité en zone d'attente, puis disqualification."], wr: [["H", "20 km — Yusuke Suzuki", "Nomi 2015", "1 h 16'36"], ["F", "20 km — Yang Jiayu", "Huangshan 2021", "1 h 23'49"]], sen: [["H", "20 km", "à renseigner", "—"], ["F", "20 km", "à renseigner", "—"]] },
  { t: "Cross-country", s: "Championnats nationaux d'hiver", tech: ["Parcours naturel, boucles de 1 500 à 2 000 m, terrain varié.", "Distances usuelles : 10 km hommes, 8 km femmes, réduites pour les catégories jeunes.", "Classement par équipes : addition des places des quatre premiers coureurs du club."], wr: [["—", "Aucun record homologué", "les parcours varient d'une édition à l'autre", "—"]], sen: [["—", "Titre national", "décerné chaque hiver à Thiès", "—"]] },
  { t: "Sauts horizontaux", s: "Longueur · triple saut", tech: ["Planche d'appel de 20 cm, mesure perpendiculaire à la trace la plus proche.", "Triple saut : cloche-pied, foulée bondissante, saut — dans cet ordre.", "Six essais, les huit meilleurs disputent les trois derniers."], wr: [["H", "Longueur — Mike Powell", "Tokyo 1991", "8,95 m"], ["F", "Longueur — Galina Tchistiakova", "Leningrad 1988", "7,52 m"], ["H", "Triple — Jonathan Edwards", "Göteborg 1995", "18,29 m"], ["F", "Triple — Yulimar Rojas", "Belgrade 2022", "15,74 m"]], sen: [["H", "Triple saut — Ndiss Kaba Badji", "Dakar 2009", "17,07 m"], ["H", "Longueur — Ndiss Kaba Badji", "Alger 2007", "8,46 m"]] },
  { t: "Sauts verticaux", s: "Hauteur · perche", tech: ["Trois essais par hauteur ; trois échecs consécutifs éliminent.", "Hauteur : franchissement dorsal, appel d'un seul pied.", "Perche : la perche peut être de n'importe quelle longueur et matériau."], wr: [["H", "Hauteur — Javier Sotomayor", "Salamanque 1993", "2,45 m"], ["F", "Hauteur — Yaroslava Mahuchikh", "Paris 2024", "2,10 m"], ["H", "Perche — Armand Duplantis", "record régulièrement amélioré", "6,30 m +"], ["F", "Perche — Yelena Isinbayeva", "Zurich 2009", "5,06 m"]], sen: [["H", "Hauteur — Mamadou Fall Sarr", "Kinshasa 2023", "2,26 m"], ["F", "Perche", "à renseigner", "—"]] },
  { t: "Lancers", s: "Poids · disque · marteau", tech: ["Aire circulaire : 2,135 m au poids, 2,50 m au disque et au marteau.", "Secteur de chute de 34,92°, mesure au centimètre inférieur.", "Engins seniors : poids 7,26 kg (H) et 4 kg (F) ; disque 2 kg et 1 kg."], wr: [["H", "Poids — Ryan Crouser", "Los Angeles 2023", "23,56 m"], ["F", "Poids — Natalya Lisovskaya", "Moscou 1987", "22,63 m"], ["H", "Disque — Mykolas Alekna", "Ramona 2024", "74,35 m"], ["F", "Marteau — Anita Włodarczyk", "Varsovie 2016", "82,98 m"]], sen: [["H", "Poids", "à renseigner", "—"], ["F", "Disque", "à renseigner", "—"]] },
  { t: "Javelot", s: "Javelot", tech: ["Élan de 30 m minimum, lancer par-dessus l'épaule.", "La pointe doit toucher le sol avant toute autre partie de l'engin.", "Engins seniors : 800 g (H) et 600 g (F)."], wr: [["H", "Jan Železný", "Iéna 1996", "98,48 m"], ["F", "Barbora Špotáková", "Stuttgart 2008", "72,28 m"]], sen: [["H", "Javelot", "à renseigner", "—"], ["F", "Javelot", "à renseigner", "—"]] },
  { t: "Relais", s: "4 × 100 m · 4 × 400 m", tech: ["Zone de transmission de 30 m ; le témoin, pas le coureur, doit y être transmis.", "Témoin creux de 28 à 30 cm, 12 cm de circonférence.", "4 × 400 m : premier relais en couloirs, rabattement ensuite."], wr: [["H", "4 × 100 m — Jamaïque", "Londres 2012", "36″84"], ["F", "4 × 100 m — États-Unis", "Londres 2012", "40″82"], ["H", "4 × 400 m — États-Unis", "Stuttgart 1993", "2'54″29"], ["F", "4 × 400 m — URSS", "Séoul 1988", "3'15″17"]], sen: [["H", "4 × 100 m — Sénégal", "Kinshasa 2023 (argent)", "—"], ["F", "4 × 400 m", "à renseigner", "—"]] },
  { t: "Marathon", s: "42,195 km · semi-marathon", tech: ["Parcours mesuré et certifié ; dénivelé négatif limité pour l'homologation.", "Ravitaillements officiels tous les 5 km.", "Au Sénégal : le Marathon Eiffage de Dakar, avec le soutien technique de la fédération."], wr: [["H", "Kelvin Kiptum", "Chicago 2023", "2 h 00'35"], ["F", "Ruth Chepngetich", "Chicago 2024", "2 h 09'56"]], sen: [["H", "Marathon", "à renseigner", "—"], ["F", "Marathon", "à renseigner", "—"]] },
  { t: "Épreuves combinées", s: "Décathlon · heptathlon", tech: ["Décathlon : 10 épreuves sur deux jours, réservé aux hommes.", "Heptathlon : 7 épreuves sur deux jours, réservé aux femmes.", "Barème de points fixé par World Athletics, identique dans le monde entier."], wr: [["H", "Décathlon — Kevin Mayer", "Talence 2018", "9 126 pts"], ["F", "Heptathlon — Jackie Joyner-Kersee", "Séoul 1988", "7 291 pts"]], sen: [["H", "Décathlon", "à renseigner", "—"], ["F", "Heptathlon", "à renseigner", "—"]] },
  { t: "Para-athlétisme", s: "Piste · concours", tech: ["Classification fonctionnelle : T pour la piste, F pour les concours.", "T11 à T13 : déficience visuelle, guide autorisé en T11.", "T51 à T54 : athlètes en fauteuil ; T61 à T64 : amputations et prothèses."], wr: [["—", "Records par classe", "établis séparément pour chaque classification", "—"]], sen: [["—", "Sélection para", "à renseigner", "—"]] },
];
